config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                                   controllers: { sessions: 'sessions'}

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do 
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
    resources :badges, only: %i[index new create destroy]
  end

  resources :badges, only: :index
  
  resource :feedbacks, only: %i[new create]
end

app/models/badge.rb
class Badge < ApplicationRecord 
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :icon_file, presence: true
  validates :name, :rule, :value, presence: true 
  validates :value, inclusion: { in: 0..Float::INFINITY }, 
                    numericality: { only_integer: true }
  validate :icon_file_existance 
  validates :rule, inclusion: { in: BadgeService::RULES.map(&:to_s) }
  
  private

  def icon_file_existance
    unless (File.exist?(ENV['IMG_BADGES_PATH'] + '/' + icon_file))
      errors.add(:icon_file, message: 'File not found')
    end
  end 
   
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: :destroy
  before_action :set_badges, only: %i[index destroy create]

  # GET /admin/badges
  def index; end

  # GET /admin/badges/new
  def new
    @badge = Badge.new
  end

  # POST /admin/badges
  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to badges_url, notice: 'Badge was successfully created.' 
    else
      render :new 
    end
  end

  # DELETE /admin/badges/1
  def destroy
    @badge.destroy
    redirect_to badges_url, notice: 'Badge was successfully destroyed.'
  end

  private
    def set_badge
      @badge = Badge.find(params[:id])
    end

    def set_badges
      @badges = Badge.all
    end

    def badge_params
      params.require(:badge).permit(:name, :icon_file, :rule, :value)
    end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: :destroy

  # GET /badges
  def index
    @badges = Badge.all
  end

end

app/helpers/badges_helper.rb
module BadgesHelper
  def mapped_rules
    BadgeService::RULES.map { |rule| [t("admin.badges.rules.#{rule}"), rule] }
  end
end

app/views/admin/badges/_badge.html.erb
<% earned_badge = current_user.user_badges.find_by(badge_id: badge.id) %>
<% if earned_badge %>
  <div class="badge-item-container pl-4 pr-4 shadow unlocked-badge">
    <%= image_tag("badges/" + badge.icon_file, class: "img-fluid p-4 w-25 d-inline-block") %>
    <span> <%= badge.name %> </span> </br> 
    <span class="earned-info"> Earned at: <%= earned_badge.created_at %> </span>
<% else %>
  <div class="badge-item-container pl-4 pr-4 shadow locked-badge">
    <%= image_tag("badges/" + badge.icon_file, class: "img-fluid p-4 w-25 d-inline-block") %>
    <span> <%= badge.name %> </span></br>
<% end %>
    <%= link_to 'Delete', admin_badge_path(badge), method: :delete %>
  </div>

app/views/admin/badges/_form.html.erb
<%= form_with(model: [:admin, @badge], local: true, class: "new_badge_form") do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :icon_file %>
    <%= form.text_field :icon_file %>
  </div>

  <h4>Правила выдачи</h4>
  <div class="field">
    <%# не понял как для селектора вызвать хелпер ведь text_method вызывается для каждого элемента коллекции, а в нашем случае элемент это просто символ %>
    <%= form.select :rule, mapped_rules, prompt: true %> 
    <%= form.text_field :value, size: 20 %> 
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/badges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Badges</h1> 
<span> | <%= link_to 'Create', new_admin_badge_path %> </span>

<div class="badges-block col-8">
  <%= render @badges %>
</div>

app/views/admin/badges/new.html.erb
<h1>New Badge</h1>

<%= render 'shared/errors', resource: @badge %>
<%= render 'form', badge: @badge %>

<%= link_to 'Back', badges_path %>