config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                                   controllers: { sessions: 'sessions'}

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do 
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
    resources :badges, only: %i[index new create destroy]
  end

  resources :badges, only: :index
  
  resource :feedbacks, only: %i[new create]
end

app/models/admin.rb
class Admin < User
  validates :last_name, presence: true
  validates :first_name, presence: true 
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true 
  validate :answers_count

  def answers_count
    unless question.answers.count.between?(0, 3)
        errors.add(:question, message: 'answers count for linked question is not in 1..4 range')
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/badge.rb
class Badge < ApplicationRecord 
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :icon_file, presence: true
  validates :name, :rule, :value, presence: true 
  validates :value, inclusion: { in: 0..Float::INFINITY }, 
                    numericality: { only_integer: true }
  validate :icon_file_existance 
  validates :rule, inclusion: { in: BadgeService::RULES.map(&:to_s) }
  
  private

  def icon_file_existance
    unless (File.exist?(ENV['IMG_BADGES_PATH'] + '/' + icon_file))
      errors.add(:icon_file, message: 'File not found')
    end
  end 
   
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope -> { order(:title) }

  has_many :tests, dependent: :nullify

  validates :title, presence: true 
end

app/models/feedback.rb
class Feedback
  include ActiveModel::Validations, ActiveModel::Model
  EMAIL_REGEX = /\A.+@.+$\z/
  attr_accessor :body, :email
  validates :email, format: { with: EMAIL_REGEX, message: "incorrect format"}
  validates :body, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
  validates :url, presence: true 
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :test_passages, class_name: 'TestPassage', foreign_key: :current_question_id
  has_many :answers, dependent: :destroy

  validates :body, presence: true 
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :author, class_name: 'User', optional: true
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  scope :easy, -> { where(level: 0..1) }
  scope :normal, -> { where(level: 2..4) }
  scope :hard, -> { where("level >= ?", 5) }
  scope :by_level, -> (level) { where(level: level) }
  scope :from_category, -> (category) do 
    joins(:category)
    .where(categories: {title: category})
    .order('categories.title DESC')
  end    

  validates :title, presence: true 
  validates :level, :time, inclusion: { in: 0..Float::INFINITY }, 
                           numericality: { only_integer: true }
  validates_uniqueness_of :title, scope: :level 
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question

  scope :completed,  -> do 
    where(current_question: nil)
  end

  scope :successful, -> do 
    where(success: true)
  end

  def timed_out? 
    Time.now > created_at.advance(minutes: test.time) 
  end 

  def completed? 
    current_question.nil? 
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids) 
    self.success = successful? 
    save!
  end

  def current_question_number
    test.questions.ids.index(current_question_id) + 1
  end

  def result 
    correct_questions.to_f / test.questions.count
  end

  def successful?
    result > SUCCESS_RATIO 
  end

  def result_percents
    "#{(result * 100).to_i}%" 
  end

  private

  SUCCESS_RATIO = 0.85

  def before_validation_set_current_question
    # Основной критерий завершенности тест - отсутствие текущего вопроса
    # По-этому добавил проверку на таймаут сюда а не в акцепт
    # иначе пришлось бы переписывать next_question добавляя туда неочевидные сложные проверки
    if persisted? && test&.time.present? && timed_out?
      self.current_question = nil 
    elsif test.present?
      self.current_question = next_question
    end
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == Array(answer_ids).reject(&:empty?).map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if new_record?
      prev_id = 0
    else
      prev_id = current_question.id
    end
    test.questions.order(:id).where('id > ?', prev_id).first
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :authored_tests, class_name: 'Test', foreign_key: :author_id, dependent: :nullify
  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :feedbacks
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges
  
  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable, 
         :validatable,
         :confirmable,
         :trackable

  def get_tests_by_level(level)
    tests.by_level(level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test: test)
  end

  def admin? 
    self.is_a?(Admin)
  end

  def has_name?
    self.first_name.present? 
  end

end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :badge
  belongs_to :user
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: %i[start]

  def index
    @tests = Test.all 
  end

  def start 
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private 

  def set_test
    @test = Test.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_year
    Time.current.year
  end

  def github_url(author, repo)
    "https://github.com/#{author}/#{repo}"
  end

  def flash_messages 
    content_tag :div, class: "flash-messages" do 
      flash.each do |key, message| 
        # насколько приемлимы условные интерполяции? 
        concat(content_tag :p, message.html_safe, 
                               class: "flash flash-#{key} alert #{flash_message_bootstrap_class(key)}"
        )
      end
    end
  end

  private 

  def flash_message_bootstrap_class(key)
    {alert: 'alert-danger', notice: 'alert-success'}[key.to_sym]
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def mapped_rules
    BadgeService::RULES.map { |rule| [t("admin.badges.rules.#{rule}"), rule] }
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      'Create new question'
    else
      'Edit question'
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/admin/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand nav-title nav-admin' %>
  <div class="nav-right-container nav-admin">
    <% if user_signed_in? %>
      <span class="nav-text"><%= t('nav.welcome') %><b><%= current_user.email %></b>  |  </span>
      <%= link_to t('nav.badges'), admin_badges_path %> | 
      <%= link_to t('nav.logout'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t('devise.links.login'), new_session_path(resource_name) %>
      <span>  |  </span>
      <%= link_to t('devise.links.register'), new_registration_path(resource_name) %>
    <% end %> 
  </div>
</nav>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= tag.div class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2><%= pluralize(resource.errors.count, 'error') %> detected: </h2>
    <ul> 
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="">
    <%= link_to 'TestGuru', root_path, class: 'navbar-brand nav-title' %>
    <% if current_user&.admin? %>
      <a href=<%= admin_tests_url %> class="admin-icon">
        <object pointer-event=none> 
          <%= octicon 'tools' %>
        </object>
      </a>
    <% end %>
  </div> 
    <div class="nav-right-container">
      <% if user_signed_in? %>
        <span class="nav-text"><%= t('nav.welcome') %><b><%= current_user.email %></b>  |  </span>     
        <%= link_to t('nav.badges'), badges_path %> |
        <%= link_to t('nav.logout'), destroy_user_session_path, method: :delete %>
      <% elsif defined?(resource_name) %>
        <%= link_to t('devise.links.login'), new_session_path(resource_name) %>
        <span>  |  </span>
        <%= link_to t('devise.links.register'), new_registration_path(resource_name) %>
      <% end %> 
    </div>
</nav>

app/views/shared/_poro_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= tag.div class: 'resource-errors' do %>
    <h2><%= pluralize(resource.errors.count, 'error') %> detected: </h2>
    <ul> 
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>