config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                                   controllers: { sessions: 'sessions'}

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do 
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
    resources :badges, only: %i[index new create destroy]
  end

  resources :badges, only: :index
  
  resource :feedbacks, only: %i[new create]
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :test_passages, class_name: 'TestPassage', foreign_key: :current_question_id
  has_many :answers, dependent: :destroy

  validates :body, presence: true 
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question

  scope :completed,  -> do 
    where(current_question: nil)
  end

  scope :successful, -> do 
    where(success: true)
  end

  def timed_out? 
    Time.now > created_at.advance(minutes: test.time) 
  end 

  def completed? 
    current_question.nil? 
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids) 
    self.success = successful? 
    save!
  end

  def current_question_number
    test.questions.ids.index(current_question_id) + 1
  end

  def result 
    correct_questions.to_f / test.questions.count
  end

  def successful?
    result > SUCCESS_RATIO 
  end

  def result_percents
    "#{(result * 100).to_i}%" 
  end

  private

  SUCCESS_RATIO = 0.85

  def before_validation_set_current_question
    # Основной критерий завершенности тест - отсутствие текущего вопроса
    # По-этому добавил проверку на таймаут сюда а не в акцепт
    # иначе пришлось бы переписывать next_question добавляя туда неочевидные сложные проверки
    if persisted? && test&.time.present? && timed_out?
      self.current_question = nil 
    elsif test.present?
      self.current_question = next_question
    end
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == Array(answer_ids).reject(&:empty?).map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if new_record?
      prev_id = 0
    else
      prev_id = current_question.id
    end
    test.questions.order(:id).where('id > ?', prev_id).first
  end

end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :set_test_passage, only: %i[show update result gist]

  def show; end

  def result
    new_badges = BadgeService.new(@test_passage).assign_new_badges
    current_user.badges << new_badges
    flash[:notice] = "New achievement unlocked!" if new_badges.present? 
  end
  
  def update
    @test_passage.accept!(params[:answer_ids])
    if @test_passage.completed?  
      redirect_to result_test_passage_path(@test_passage)
    else
       render :show
    end
  end 
  
  def gist
    # строка нужна, тк в условии нам нужно обратиться к тому же экземпляру сервиса для получена статуса последнего запроса
    service = gist_service
    result = service.call
    if service.success?
      @gist = Gist.create(url: result.html_url, hash_code: result.id, 
                                                     user: current_user, 
                                                 question: @test_passage.current_question
                         ) 
      flash[:notice] = t('.success').concat(%Q[<a href="#{@gist.url}"> #{t('.link')}</a>])
    else 
      flash[:alert] = t('.failure') 
    end
    redirect_to @test_passage
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def gist_service
    octokit_client = Octokit::Client.new(access_token: ENV['GITHUB_TOKEN'])
    GistQuestionService.new(@test_passage.current_question, octokit_client)
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<% if @test_passage.successful? %>
  <h2 class="success"><%= @test_passage.test.title %> was completed!</h2>
<% else %> 
  <h2 class="fail"><%= @test_passage.test.title %> is failed!</h2>
<% end %>
<p>Result: <%= @test_passage.result_percents %></p>
<%= link_to 'Return to tests', tests_path %>

app/views/test_passages/show.html.erb
<h2> Passing the <%= @test_passage.test.title %></h2>

<% if @test_passage.test.time %>
    <div class="timer">
      <p id="start-time"> <%= @test_passage.created_at.to_i %> </p>
      <p class="test-time">
        <%= t('tests.time.label') %>: 
        <span id="time-minutes"><%= @test_passage.test.time %></span>
        <%= t('tests.time.measure') %>  
      </p>
      <p class="clock">
        <%# JS timer here %> 
      </p>
    </div>
<% end %>

<%= tag.div class: "progress-container",
            data: { question_number: @test_passage.current_question_number,
                    questions_count: @test_passage.test.questions.count } do %>
  <p>
    Question <%= @test_passage.current_question_number %> of <%= @test_passage.test.questions.count %>
  </p>
  
  <div class="vanilla-progress-bar">
    <div class="bar-status">
    </div>
  </div>
<% end %> 

<b>
  <%= @test_passage.current_question.body %>
</b>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body do |b| %>
    <%= b.check_box id: "answer_ids_#{b.object.id}" %>
    <%= b.label %>
  <% end %>
  <p><%= link_to 'Gist Question', gist_test_passage_path(@test_passage), method: :post %></p>
  <p> <%= form.submit 'Next' %> </p>
<% end %>