config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                                   controllers: { sessions: 'sessions'}

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do 
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
    resources :badges, only: %i[index new create destroy]
  end

  resources :badges, only: :index
  
  resource :feedbacks, only: %i[new create]
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true 
  validate :answers_count

  def answers_count
    unless question.answers.count.between?(0, 3)
        errors.add(:question, message: 'answers count for linked question is not in 1..4 range')
    end
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :set_answer, only: %i[show edit update destroy]
  before_action :set_question, only: %i[new create]

  def show; end 

  def new
    @answer = Answer.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to admin_answer_path(@answer)
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params) 
      redirect_to admin_answer_path(@answer)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private

    def set_question
      @question = Question.find(params[:question_id])
    end

    def set_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:body, :correct)
    end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: %i[show edit update destroy]
  before_action :set_question, only: %i[new create]

  def show; end 

  def new
    @answer = Answer.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to @answer
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params) 
      redirect_to @answer
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to @answer.question
  end

  private

    def set_question
      @question = Question.find(params[:question_id])
    end

    def set_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:body, :correct)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body %> <br>
  <%= link_to 'Show', admin_answer_path(answer) %> |
  <%= link_to 'Edit', edit_admin_answer_path(answer) %> |
  <%= link_to 'Delete', 
              admin_answer_path(answer), 
              method: :delete,
              data: { confirm: 'Are you sure?'} %>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :answer_body, cols: 60, rows: 7 %>
  </p>
  <p>
    <%= form.label :correct %><br>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>
    <%= form.submit %>
  
<% end %>

app/views/admin/answers/edit.html.erb
<h3>Editing Answer</h3>
<p> 
  <%= @answer.question.body %>
</p>

<%= render 'shared/errors', resource: @answer %>
<%= render 'form', answer: @answer %>

<%= link_to 'Show', admin_answer_path(@answer) %> |
<%= link_to 'Back', admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h3>New Answer</h3>
<p> 
  <%= @question.body %>
</p>

<%= render 'shared/errors', resource: @answer %>
<%= render 'form', answer: @answer %>

<%= link_to 'Back', admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<h4><%= @answer.question.body %> </h4>
<p ><%= @answer.body %></p>
<p> <%= @answer.correct %> </p>

<%= link_to 'Back', admin_question_path(@answer.question) %>